### Holt Winter

In [2]:
%pip install statsmodels

Requirement already satisfied: statsmodels in c:\users\ahmed\anaconda3\lib\site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\ahmed\anaconda3\lib\site-packages (from statsmodels) (2.3.5)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in c:\users\ahmed\anaconda3\lib\site-packages (from statsmodels) (1.16.3)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\ahmed\anaconda3\lib\site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: patsy>=0.5.6 in c:\users\ahmed\anaconda3\lib\site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in c:\users\ahmed\anaconda3\lib\site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ahmed\anaconda3\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ahmed\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
from statsmodels.tsa.holtwinters import ExponentialSmoothing

In [4]:
df = pd.read_csv(r"C:\Users\ahmed\Documents\Data Science LUXDEV\PPORTFOLIO PROJECTS\INVENTORY FORECASTING\CSV\CLEAN\feature_engineered_sales.csv")
pd.set_option('display.max_columns',None)
df.head()

,product_id,product_name_x,category_x,units_sold,unit_price_x,promotion_flag,stock_level_end_of_day,stockout_flag,date,product_name_y,category_y,unit_cost,unit_price_y,lead_time_days,safety_stock_days,day_of_week,is_weekend,Month,Quarter,is_festive,day_of_year,Revenue,rolling_7d_avg,rolling_28d_avg,previous_day_sale,previous_week_sale,days_since_last_promo
0,SKU001,Soda 500ml,Beverages,29,154.61,False,365.9,False,2024-01-01,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,1,1,False,1,4483.69,29.0,29.0,NaN,NaN,0
1,SKU001,Soda 500ml,Beverages,27,154.61,False,338.9,False,2024-01-02,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,1,1,False,2,4174.47,28.0,28.0,29.0,NaN,0
2,SKU001,Soda 500ml,Beverages,25,154.61,False,313.9,False,2024-01-03,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,1,1,False,3,3865.25,27.0,27.0,27.0,NaN,0
3,SKU001,Soda 500ml,Beverages,33,154.61,True,280.9,False,2024-01-04,Soda 500ml,Beverages,126.94,154.61,5,4,Thursday,False,1,1,False,4,5102.13,28.5,28.5,25.0,NaN,0
4,SKU001,Soda 500ml,Beverages,26,154.61,False,254.9,False,2024-01-05,Soda 500ml,Beverages,126.94,154.61,5,4,Friday,False,1,1,False,5,4019.86,28.0,28.0,33.0,NaN,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18275 entries, 0 to 18274
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              18275 non-null  object
 1   product_name_x          18275 non-null  object
 2   category_x              18275 non-null  object
 3   units_sold              18275 non-null  int64
 4   unit_price_x            18275 non-null  float64
 5   promotion_flag          18275 non-null  bool
 6   stock_level_end_of_day  18275 non-null  float64
 7   stockout_flag           18275 non-null  bool
 8   date                    18275 non-null  object
 9   product_name_y          18275 non-null  object
 10  category_y              18275 non-null  object
 11  unit_cost               18275 non-null  float64
 12  unit_price_y            18275 non-null  float64
 13  lead_time_days          18275 non-null  int64
 14  safety_stock_days       18275 non-null  int64
 15  day_of_week             18275 non-null  object
 16  is_weekend              18275 non-null  bool
 17  Month                   18275 non-null  int64
 18  Quarter                 18275 non-null  int64
 19  is_festive              18275 non-null  bool
 20  day_of_year             18275 non-null  int64
 21  Revenue                 18275 non-null  float64
 22  rolling_7d_avg          18275 non-null  float64
 23  rolling_28d_avg         18275 non-null  float64
 24  previous_day_sale       18250 non-null  float64
 25  previous_week_sale      18100 non-null  float64
 26  days_since_last_promo   18275 non-null  int64
dtypes: bool(4), float64(9), int64(7), object(7)
memory usage: 3.3+ MB

In [6]:
df['date']= pd.to_datetime(df['date'])
df.sort_values(['product_id','date'])

,product_id,product_name_x,category_x,units_sold,unit_price_x,promotion_flag,stock_level_end_of_day,stockout_flag,date,product_name_y,category_y,unit_cost,unit_price_y,lead_time_days,safety_stock_days,day_of_week,is_weekend,Month,Quarter,is_festive,day_of_year,Revenue,rolling_7d_avg,rolling_28d_avg,previous_day_sale,previous_week_sale,days_since_last_promo
0,SKU001,Soda 500ml,Beverages,29,154.61,False,365.9,False,2024-01-01,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,1,1,False,1,4483.69,29.000000,29.000000,NaN,NaN,0
1,SKU001,Soda 500ml,Beverages,27,154.61,False,338.9,False,2024-01-02,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,1,1,False,2,4174.47,28.000000,28.000000,29.0,NaN,0
2,SKU001,Soda 500ml,Beverages,25,154.61,False,313.9,False,2024-01-03,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,1,1,False,3,3865.25,27.000000,27.000000,27.0,NaN,0
3,SKU001,Soda 500ml,Beverages,33,154.61,True,280.9,False,2024-01-04,Soda 500ml,Beverages,126.94,154.61,5,4,Thursday,False,1,1,False,4,5102.13,28.500000,28.500000,25.0,NaN,0
4,SKU001,Soda 500ml,Beverages,26,154.61,False,254.9,False,2024-01-05,Soda 500ml,Beverages,126.94,154.61,5,4,Friday,False,1,1,False,5,4019.86,28.000000,28.000000,33.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18270,SKU025,Sukuma Wiki Bunch,Produce,75,43.39,False,716.8,False,2025-12-27,Sukuma Wiki Bunch,Produce,63.20,43.39,8,2,Saturday,True,12,4,True,361,3254.25,71.571429,72.035714,85.0,88.0,0
18271,SKU025,Sukuma Wiki Bunch,Produce,87,43.39,False,629.8,False,2025-12-28,Sukuma Wiki Bunch,Produce,63.20,43.39,8,2,Sunday,True,12,4,True,362,3774.93,71.857143,71.500000,75.0,85.0,0
18272,SKU025,Sukuma Wiki Bunch,Produce,58,43.39,False,571.8,False,2025-12-29,Sukuma Wiki Bunch,Produce,63.20,43.39,8,2,Monday,False,12,4,True,363,2516.62,70.285714,70.678571,87.0,69.0,0
18273,SKU025,Sukuma Wiki Bunch,Produce,79,43.39,False,492.8,False,2025-12-30,Sukuma Wiki Bunch,Produce,63.20,43.39,8,2,Tuesday,False,12,4,True,364,3427.81,72.000000,70.392857,58.0,67.0,0
18274,SKU025,Sukuma Wiki Bunch,Produce,73,43.39,False,419.8,False,2025-12-31,Sukuma Wiki Bunch,Produce,63.20,43.39,8,2,Wednesday,False,12,4,True,365,3167.47,73.000000,71.428571,79.0,66.0,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18275 entries, 0 to 18274
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              18275 non-null  object
 1   product_name_x          18275 non-null  object
 2   category_x              18275 non-null  object
 3   units_sold              18275 non-null  int64
 4   unit_price_x            18275 non-null  float64
 5   promotion_flag          18275 non-null  bool
 6   stock_level_end_of_day  18275 non-null  float64
 7   stockout_flag           18275 non-null  bool
 8   date                    18275 non-null  datetime64[ns]
 9   product_name_y          18275 non-null  object
 10  category_y              18275 non-null  object
 11  unit_cost               18275 non-null  float64
 12  unit_price_y            18275 non-null  float64
 13  lead_time_days          18275 non-null  int64
 14  safety_stock_days       18275 non-null  int64
 15  day_of_week             18275 non-null  object
 16  is_weekend              18275 non-null  bool
 17  Month                   18275 non-null  int64
 18  Quarter                 18275 non-null  int64
 19  is_festive              18275 non-null  bool
 20  day_of_year             18275 non-null  int64
 21  Revenue                 18275 non-null  float64
 22  rolling_7d_avg          18275 non-null  float64
 23  rolling_28d_avg         18275 non-null  float64
 24  previous_day_sale       18250 non-null  float64
 25  previous_week_sale      18100 non-null  float64
 26  days_since_last_promo   18275 non-null  int64
dtypes: bool(4), datetime64[ns](1), float64(9), int64(7), object(6)
memory usage: 3.3+ MB

**NOTE** We essentially want to predict future sales per product , but currently our model will just be giving future sales jumping from one product to another. So we have to separate dataframes as per products

**Product_001(df_beverages)**

In [8]:
df_beverages = df[df['product_id']== 'SKU001'].copy()
df_beverages.sort_values('date')
df_beverages

,product_id,product_name_x,category_x,units_sold,unit_price_x,promotion_flag,stock_level_end_of_day,stockout_flag,date,product_name_y,category_y,unit_cost,unit_price_y,lead_time_days,safety_stock_days,day_of_week,is_weekend,Month,Quarter,is_festive,day_of_year,Revenue,rolling_7d_avg,rolling_28d_avg,previous_day_sale,previous_week_sale,days_since_last_promo
0,SKU001,Soda 500ml,Beverages,29,154.61,False,365.9,False,2024-01-01,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,1,1,False,1,4483.69,29.000000,29.000000,NaN,NaN,0
1,SKU001,Soda 500ml,Beverages,27,154.61,False,338.9,False,2024-01-02,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,1,1,False,2,4174.47,28.000000,28.000000,29.0,NaN,0
2,SKU001,Soda 500ml,Beverages,25,154.61,False,313.9,False,2024-01-03,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,1,1,False,3,3865.25,27.000000,27.000000,27.0,NaN,0
3,SKU001,Soda 500ml,Beverages,33,154.61,True,280.9,False,2024-01-04,Soda 500ml,Beverages,126.94,154.61,5,4,Thursday,False,1,1,False,4,5102.13,28.500000,28.500000,25.0,NaN,0
4,SKU001,Soda 500ml,Beverages,26,154.61,False,254.9,False,2024-01-05,Soda 500ml,Beverages,126.94,154.61,5,4,Friday,False,1,1,False,5,4019.86,28.000000,28.000000,33.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,SKU001,Soda 500ml,Beverages,71,154.61,False,60.8,False,2025-12-27,Soda 500ml,Beverages,126.94,154.61,5,4,Saturday,True,12,4,True,361,10977.31,48.714286,46.750000,35.0,67.0,0
727,SKU001,Soda 500ml,Beverages,66,154.61,False,651.2,False,2025-12-28,Soda 500ml,Beverages,126.94,154.61,5,4,Sunday,True,12,4,True,362,10204.26,50.000000,47.285714,71.0,57.0,0
728,SKU001,Soda 500ml,Beverages,46,154.61,False,605.2,False,2025-12-29,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,12,4,True,363,7112.06,49.285714,47.607143,66.0,51.0,0
729,SKU001,Soda 500ml,Beverages,45,154.61,False,560.2,False,2025-12-30,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,12,4,True,364,6957.45,48.714286,47.535714,46.0,49.0,0
730,SKU001,Soda 500ml,Beverages,41,154.61,False,519.2,False,2025-12-31,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,12,4,True,365,6339.01,49.142857,47.357143,45.0,38.0,0

**dividing our data into train_data and test_data**

In [54]:
holdout_days = 31

series = df_beverages['units_sold'].to_numpy(dtype=float)
dates = df_beverages['date'].to_numpy()

train_beverages = series[:-holdout_days]
test_beverages = series[-holdout_days:]
test_dates = dates[-holdout_days:]

In [56]:
test_beverages

array([37., 47., 46., 39., 39., 48., 48., 42., 49., 50., 46., 47., 63.,
       41., 48., 55., 33., 27., 45., 67., 57., 51., 49., 38., 40., 35.,
       71., 66., 46., 45., 41.])

**predicting sales for the next 31 days using the holt winter forecast**

In [255]:
def holt_winter_forecast(y,horizon,season_length=7):
    model=ExponentialSmoothing(
        y,
        trend='add',
        seasonal='add',
        seasonal_periods=season_length
    )
    fitted_model = model.fit()
    forecast = fitted_model.forecast(horizon)
    return np.maximum(0,forecast)

Sales = train_beverages
future = holt_winter_forecast(Sales,holdout_days)
print(future)


#basically takes the last 84 days of the train data, observes trends, seasonality,and use those observations to predict values for the next 31 days

[45.2026318  46.4147035  46.48292745 46.07312872 45.45421439 54.58434008
 52.91325168 45.3768004  46.58887209 46.65709605 46.24729731 45.62838299
 54.75850868 53.08742028 45.550969   46.76304069 46.83126464 46.42146591
 45.80255159 54.93267728 53.26158887 45.7251376  46.93720929 47.00543324
 46.59563451 45.97672018 55.10684588 53.43575747 45.89930619 47.11137789
 47.17960184]

In [256]:
forecast_table= pd.DataFrame({'Forecast':future,
                                 'Actual':test_beverages})
print(forecast_table)

     Forecast  Actual
0   45.202632    37.0
1   46.414703    47.0
2   46.482927    46.0
3   46.073129    39.0
4   45.454214    39.0
5   54.584340    48.0
6   52.913252    48.0
7   45.376800    42.0
8   46.588872    49.0
9   46.657096    50.0
10  46.247297    46.0
11  45.628383    47.0
12  54.758509    63.0
13  53.087420    41.0
14  45.550969    48.0
15  46.763041    55.0
16  46.831265    33.0
17  46.421466    27.0
18  45.802552    45.0
19  54.932677    67.0
20  53.261589    57.0
21  45.725138    51.0
22  46.937209    49.0
23  47.005433    38.0
24  46.595635    40.0
25  45.976720    35.0
26  55.106846    71.0
27  53.435757    66.0
28  45.899306    46.0
29  47.111378    45.0
30  47.179602    41.0

In [257]:
forecast_table['AbsoluteError'] = (forecast_table['Actual']-forecast_table['Forecast']).abs()

In [258]:
forecast_table

     Forecast  Actual  AbsoluteError
0   45.202632    37.0       8.202632
1   46.414703    47.0       0.585297
2   46.482927    46.0       0.482927
3   46.073129    39.0       7.073129
4   45.454214    39.0       6.454214
5   54.584340    48.0       6.584340
6   52.913252    48.0       4.913252
7   45.376800    42.0       3.376800
8   46.588872    49.0       2.411128
9   46.657096    50.0       3.342904
10  46.247297    46.0       0.247297
11  45.628383    47.0       1.371617
12  54.758509    63.0       8.241491
13  53.087420    41.0      12.087420
14  45.550969    48.0       2.449031
15  46.763041    55.0       8.236959
16  46.831265    33.0      13.831265
17  46.421466    27.0      19.421466
18  45.802552    45.0       0.802552
19  54.932677    67.0      12.067323
20  53.261589    57.0       3.738411
21  45.725138    51.0       5.274862
22  46.937209    49.0       2.062791
23  47.005433    38.0       9.005433
24  46.595635    40.0       6.595635
25  45.976720    35.0      10.976720
26  55.106846    71.0      15.893154
27  53.435757    66.0      12.564243
28  45.899306    46.0       0.100694
29  47.111378    45.0       2.111378
30  47.179602    41.0       6.179602

In [259]:
mae= forecast_table['AbsoluteError'].mean()
print(mae)

6.344708591568669

In [260]:
rmse = np.sqrt(((forecast_table['Actual']-forecast_table['Forecast'])**2).mean())
print(rmse)

8.040740633489015

**NOTE:** The more you increase the window for observation the more acurate your data is, currently our model of ExponentialSmoothing is taking the last 28 days of our train data and observing the trend and seasonality of that data to forecast values for the next 31 days. Errors stand at(`mae`: 6.14, `rmse`:7.71).I was wrong , increasing the window doesnt necessarily accurate our data more.Currently we are increasing our window in steps of 7, we are currently observing from a window of 42(`mae`:6.1 , `rmse`:7.5), At 56 (`mae`:5.8, `rmse`: 7.6), At 84(`mae`:5.6, `rmse`:7.3)

### Seasonal Naive

In [17]:
df_beverages

,product_id,product_name_x,category_x,units_sold,unit_price_x,promotion_flag,stock_level_end_of_day,stockout_flag,date,product_name_y,category_y,unit_cost,unit_price_y,lead_time_days,safety_stock_days,day_of_week,is_weekend,Month,Quarter,is_festive,day_of_year,Revenue,rolling_7d_avg,rolling_28d_avg,previous_day_sale,previous_week_sale,days_since_last_promo
0,SKU001,Soda 500ml,Beverages,29,154.61,False,365.9,False,2024-01-01,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,1,1,False,1,4483.69,29.000000,29.000000,NaN,NaN,0
1,SKU001,Soda 500ml,Beverages,27,154.61,False,338.9,False,2024-01-02,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,1,1,False,2,4174.47,28.000000,28.000000,29.0,NaN,0
2,SKU001,Soda 500ml,Beverages,25,154.61,False,313.9,False,2024-01-03,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,1,1,False,3,3865.25,27.000000,27.000000,27.0,NaN,0
3,SKU001,Soda 500ml,Beverages,33,154.61,True,280.9,False,2024-01-04,Soda 500ml,Beverages,126.94,154.61,5,4,Thursday,False,1,1,False,4,5102.13,28.500000,28.500000,25.0,NaN,0
4,SKU001,Soda 500ml,Beverages,26,154.61,False,254.9,False,2024-01-05,Soda 500ml,Beverages,126.94,154.61,5,4,Friday,False,1,1,False,5,4019.86,28.000000,28.000000,33.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,SKU001,Soda 500ml,Beverages,71,154.61,False,60.8,False,2025-12-27,Soda 500ml,Beverages,126.94,154.61,5,4,Saturday,True,12,4,True,361,10977.31,48.714286,46.750000,35.0,67.0,0
727,SKU001,Soda 500ml,Beverages,66,154.61,False,651.2,False,2025-12-28,Soda 500ml,Beverages,126.94,154.61,5,4,Sunday,True,12,4,True,362,10204.26,50.000000,47.285714,71.0,57.0,0
728,SKU001,Soda 500ml,Beverages,46,154.61,False,605.2,False,2025-12-29,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,12,4,True,363,7112.06,49.285714,47.607143,66.0,51.0,0
729,SKU001,Soda 500ml,Beverages,45,154.61,False,560.2,False,2025-12-30,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,12,4,True,364,6957.45,48.714286,47.535714,46.0,49.0,0
730,SKU001,Soda 500ml,Beverages,41,154.61,False,519.2,False,2025-12-31,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,12,4,True,365,6339.01,49.142857,47.357143,45.0,38.0,0

In [18]:
holdout_days = 31
season_length = 7

series = df_beverages['units_sold'].to_numpy(dtype=float)
dates = df_beverages['date'].to_numpy()

if len(series)< (holdout_days + season_length):
    raise ValueError('Not enough history for a 31 day hold out and a 7 day season!')

train_data = series[:-holdout_days]
test_data = series[-holdout_days:]
test_dates=dates[-holdout_days:]

print(f"Training data: {len(train_data)} days")
print(f"Holdout/testing data: {len(test_data)} days ")

def seasonal_naive_forecast(y, horizon, season=7):
    last_season = y[-season:]
    reps = int(np.ceil(horizon/season))
    x = np.tile(last_season,reps)[:horizon]
    return x


future = seasonal_naive_forecast(train_data,holdout_days)
print(future)

Training data: 700 days
Holdout/testing data: 31 days
[30. 45. 36. 58. 50. 60. 51. 30. 45. 36. 58. 50. 60. 51. 30. 45. 36. 58.
 50. 60. 51. 30. 45. 36. 58. 50. 60. 51. 30. 45. 36.]

In [19]:
Actual = df_beverages['units_sold'].iloc[-31:]

In [20]:
forecast_table = pd.DataFrame({'Actual':Actual,
                               'forecast':future})
forecast_table

     Actual  forecast
700      37      30.0
701      47      45.0
702      46      36.0
703      39      58.0
704      39      50.0
705      48      60.0
706      48      51.0
707      42      30.0
708      49      45.0
709      50      36.0
710      46      58.0
711      47      50.0
712      63      60.0
713      41      51.0
714      48      30.0
715      55      45.0
716      33      36.0
717      27      58.0
718      45      50.0
719      67      60.0
720      57      51.0
721      51      30.0
722      49      45.0
723      38      36.0
724      40      58.0
725      35      50.0
726      71      60.0
727      66      51.0
728      46      30.0
729      45      45.0
730      41      36.0

In [21]:
forecast_table['AbsoluteError'] = (forecast_table['Actual']- forecast_table['forecast']).abs()

In [22]:
forecast_table

     Actual  forecast  AbsoluteError
700      37      30.0            7.0
701      47      45.0            2.0
702      46      36.0           10.0
703      39      58.0           19.0
704      39      50.0           11.0
705      48      60.0           12.0
706      48      51.0            3.0
707      42      30.0           12.0
708      49      45.0            4.0
709      50      36.0           14.0
710      46      58.0           12.0
711      47      50.0            3.0
712      63      60.0            3.0
713      41      51.0           10.0
714      48      30.0           18.0
715      55      45.0           10.0
716      33      36.0            3.0
717      27      58.0           31.0
718      45      50.0            5.0
719      67      60.0            7.0
720      57      51.0            6.0
721      51      30.0           21.0
722      49      45.0            4.0
723      38      36.0            2.0
724      40      58.0           18.0
725      35      50.0           15.0
726      71      60.0           11.0
727      66      51.0           15.0
728      46      30.0           16.0
729      45      45.0            0.0
730      41      36.0            5.0

In [23]:
mae = forecast_table['AbsoluteError'].mean()
print(mae)

9.96774193548387

In [24]:
rmse = np.sqrt(((forecast_table['Actual']-forecast_table['forecast'])**2).mean())
print(rmse)

12.111045345255658

### Moving 7 day average

In [25]:
df_beverages

,product_id,product_name_x,category_x,units_sold,unit_price_x,promotion_flag,stock_level_end_of_day,stockout_flag,date,product_name_y,category_y,unit_cost,unit_price_y,lead_time_days,safety_stock_days,day_of_week,is_weekend,Month,Quarter,is_festive,day_of_year,Revenue,rolling_7d_avg,rolling_28d_avg,previous_day_sale,previous_week_sale,days_since_last_promo
0,SKU001,Soda 500ml,Beverages,29,154.61,False,365.9,False,2024-01-01,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,1,1,False,1,4483.69,29.000000,29.000000,NaN,NaN,0
1,SKU001,Soda 500ml,Beverages,27,154.61,False,338.9,False,2024-01-02,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,1,1,False,2,4174.47,28.000000,28.000000,29.0,NaN,0
2,SKU001,Soda 500ml,Beverages,25,154.61,False,313.9,False,2024-01-03,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,1,1,False,3,3865.25,27.000000,27.000000,27.0,NaN,0
3,SKU001,Soda 500ml,Beverages,33,154.61,True,280.9,False,2024-01-04,Soda 500ml,Beverages,126.94,154.61,5,4,Thursday,False,1,1,False,4,5102.13,28.500000,28.500000,25.0,NaN,0
4,SKU001,Soda 500ml,Beverages,26,154.61,False,254.9,False,2024-01-05,Soda 500ml,Beverages,126.94,154.61,5,4,Friday,False,1,1,False,5,4019.86,28.000000,28.000000,33.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,SKU001,Soda 500ml,Beverages,71,154.61,False,60.8,False,2025-12-27,Soda 500ml,Beverages,126.94,154.61,5,4,Saturday,True,12,4,True,361,10977.31,48.714286,46.750000,35.0,67.0,0
727,SKU001,Soda 500ml,Beverages,66,154.61,False,651.2,False,2025-12-28,Soda 500ml,Beverages,126.94,154.61,5,4,Sunday,True,12,4,True,362,10204.26,50.000000,47.285714,71.0,57.0,0
728,SKU001,Soda 500ml,Beverages,46,154.61,False,605.2,False,2025-12-29,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,12,4,True,363,7112.06,49.285714,47.607143,66.0,51.0,0
729,SKU001,Soda 500ml,Beverages,45,154.61,False,560.2,False,2025-12-30,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,12,4,True,364,6957.45,48.714286,47.535714,46.0,49.0,0
730,SKU001,Soda 500ml,Beverages,41,154.61,False,519.2,False,2025-12-31,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,12,4,True,365,6339.01,49.142857,47.357143,45.0,38.0,0

In [36]:
holdout_days = 31
season_length = 7

series = df_beverages['units_sold'].to_numpy(dtype=float)
dates = df_beverages['date'].to_numpy()

if len(series) < holdout_days + season_length:
    raise ValueError("Not enough history for a 31-day holdout plus a 7-day window.")
    
train_data = series[:-holdout_days]
test_data = series[-holdout_days:]
test_dates=dates[-holdout_days:]

print(f"Training data: first {len(train_data)} days of our dataset")
print(f"Testing_data: the last {len(test_data)} days of our dataset")

def moving_average(y,steps, season_length=7):
    history = list(y)
    future =[]

    for _ in range(steps):
        avg = np.mean(history[-season_length:])
        future.append(avg)
        history.append(avg)
    x = np.array(future)
    return x

future_x = moving_average(train_data,holdout_days)
print(future_x)

Training data: first 700 days of our dataset
Testing_data: the last 31 days of our dataset
[47.14285714 49.59183673 50.24781341 52.28321533 51.4665318  51.67603635
 50.48689868 50.41359849 50.88084726 51.06499162 51.18173136 51.02437651
 50.96121147 50.85909363 50.91226433 50.98350231 50.99816732 50.98862099
 50.96103379 50.95198483 50.95066674 50.96374862 50.97110351 50.96933226
 50.96521296 50.96186896 50.96198827 50.96341733 50.96523884 50.96545173
 50.96464434]

In [37]:
Actual = df_beverages['units_sold'].iloc[-31:]

In [38]:
forecast_table = pd.DataFrame({'Actual':Actual,
                               'Forecast':future_x})
forecast_table

     Actual   Forecast
700      37  47.142857
701      47  49.591837
702      46  50.247813
703      39  52.283215
704      39  51.466532
705      48  51.676036
706      48  50.486899
707      42  50.413598
708      49  50.880847
709      50  51.064992
710      46  51.181731
711      47  51.024377
712      63  50.961211
713      41  50.859094
714      48  50.912264
715      55  50.983502
716      33  50.998167
717      27  50.988621
718      45  50.961034
719      67  50.951985
720      57  50.950667
721      51  50.963749
722      49  50.971104
723      38  50.969332
724      40  50.965213
725      35  50.961869
726      71  50.961988
727      66  50.963417
728      46  50.965239
729      45  50.965452
730      41  50.964644

In [39]:
forecast_table['AbsoluteError']= (forecast_table['Actual']-forecast_table['Forecast']).abs()
forecast_table

     Actual   Forecast  AbsoluteError
700      37  47.142857      10.142857
701      47  49.591837       2.591837
702      46  50.247813       4.247813
703      39  52.283215      13.283215
704      39  51.466532      12.466532
705      48  51.676036       3.676036
706      48  50.486899       2.486899
707      42  50.413598       8.413598
708      49  50.880847       1.880847
709      50  51.064992       1.064992
710      46  51.181731       5.181731
711      47  51.024377       4.024377
712      63  50.961211      12.038789
713      41  50.859094       9.859094
714      48  50.912264       2.912264
715      55  50.983502       4.016498
716      33  50.998167      17.998167
717      27  50.988621      23.988621
718      45  50.961034       5.961034
719      67  50.951985      16.048015
720      57  50.950667       6.049333
721      51  50.963749       0.036251
722      49  50.971104       1.971104
723      38  50.969332      12.969332
724      40  50.965213      10.965213
725      35  50.961869      15.961869
726      71  50.961988      20.038012
727      66  50.963417      15.036583
728      46  50.965239       4.965239
729      45  50.965452       5.965452
730      41  50.964644       9.964644

In [40]:
mae = forecast_table['AbsoluteError'].mean()
print(mae)

8.587298315226356

In [41]:
rmse = np.sqrt(((forecast_table['Actual']-forecast_table['Forecast'])**2).mean())
print(rmse)

10.51537550657124

The above method for the 7 day moving average was recursive .We decided to use the average of the last 7 days of our training data to forcast the next value, then we kept on moving the window one value to the next for the rest of the 31 days hold out.
Note this method is not so accurate since it evens out the trends and seasonality so it pretty much doesnt capture it. The best method is to use the last 7 days mean to forecast the next 31 days

In [249]:
def rolling_average(y, steps, season_length=7):
    avg = y[-season_length:].mean()
    x =np.repeat(avg, steps)
    return x

future = rolling_average(train_data, holdout_days) 
print(future)

#currently we are observing from the last 7 days of our data

[47.14285714 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714
 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714
 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714
 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714
 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714 47.14285714
 47.14285714]

In [250]:
Actual = df_beverages['units_sold'].iloc[-31:]

In [251]:
forecast_table = pd.DataFrame({'Actual':Actual,
                               'Forecast':future})
forecast_table

     Actual   Forecast
700      37  47.142857
701      47  47.142857
702      46  47.142857
703      39  47.142857
704      39  47.142857
705      48  47.142857
706      48  47.142857
707      42  47.142857
708      49  47.142857
709      50  47.142857
710      46  47.142857
711      47  47.142857
712      63  47.142857
713      41  47.142857
714      48  47.142857
715      55  47.142857
716      33  47.142857
717      27  47.142857
718      45  47.142857
719      67  47.142857
720      57  47.142857
721      51  47.142857
722      49  47.142857
723      38  47.142857
724      40  47.142857
725      35  47.142857
726      71  47.142857
727      66  47.142857
728      46  47.142857
729      45  47.142857
730      41  47.142857

In [252]:
forecast_table['AbsoluteError']= (forecast_table['Actual']-forecast_table['Forecast']).abs()
forecast_table

     Actual   Forecast  AbsoluteError
700      37  47.142857      10.142857
701      47  47.142857       0.142857
702      46  47.142857       1.142857
703      39  47.142857       8.142857
704      39  47.142857       8.142857
705      48  47.142857       0.857143
706      48  47.142857       0.857143
707      42  47.142857       5.142857
708      49  47.142857       1.857143
709      50  47.142857       2.857143
710      46  47.142857       1.142857
711      47  47.142857       0.142857
712      63  47.142857      15.857143
713      41  47.142857       6.142857
714      48  47.142857       0.857143
715      55  47.142857       7.857143
716      33  47.142857      14.142857
717      27  47.142857      20.142857
718      45  47.142857       2.142857
719      67  47.142857      19.857143
720      57  47.142857       9.857143
721      51  47.142857       3.857143
722      49  47.142857       1.857143
723      38  47.142857       9.142857
724      40  47.142857       7.142857
725      35  47.142857      12.142857
726      71  47.142857      23.857143
727      66  47.142857      18.857143
728      46  47.142857       1.142857
729      45  47.142857       2.142857
730      41  47.142857       6.142857

In [253]:
mae = forecast_table['AbsoluteError'].mean()
print(mae)

7.216589861751151

In [254]:
rmse = np.sqrt(((forecast_table['Actual']-forecast_table['Forecast'])**2).mean())
print(rmse)

9.83725369384149

Avoiding the recursive method, will generate more acurate values.You can see that from the **rmse** and **mae**.

**NOTE:** currently we are observing our data from a window of 7 days, taking the average of those last 7 days from our training data to predict the next 31 values and find errors.At 7(`mae`:7.2, `rmse`:9.8).At 28(`mae`:7.3, `rmse`:9.9).At 84 (`mae`:7.2, `rmse`:9.9).

In [ ]:
#SUMMARY
#Moving 7 day average forecast, window of 7 days : mae: 7.2, rmse: 9.8
#Holt winter(ExponentialSmoothing) forecast, window of 84 days: mae:5.6, rmse:7.3
#Holt winter forecast, window of 7 days: mae:6.3, rmse:8.0

We can now decide to predict values for our product using Holt winter (ExponentialSmoothing).The method shows more accuracy than the rest.We will predict values for the next 14 days for that specific product , and we will use a window of 7 days.

In [261]:
df_beverages

,product_id,product_name_x,category_x,units_sold,unit_price_x,promotion_flag,stock_level_end_of_day,stockout_flag,date,product_name_y,category_y,unit_cost,unit_price_y,lead_time_days,safety_stock_days,day_of_week,is_weekend,Month,Quarter,is_festive,day_of_year,Revenue,rolling_7d_avg,rolling_28d_avg,previous_day_sale,previous_week_sale,days_since_last_promo
0,SKU001,Soda 500ml,Beverages,29,154.61,False,365.9,False,2024-01-01,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,1,1,False,1,4483.69,29.000000,29.000000,NaN,NaN,0
1,SKU001,Soda 500ml,Beverages,27,154.61,False,338.9,False,2024-01-02,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,1,1,False,2,4174.47,28.000000,28.000000,29.0,NaN,0
2,SKU001,Soda 500ml,Beverages,25,154.61,False,313.9,False,2024-01-03,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,1,1,False,3,3865.25,27.000000,27.000000,27.0,NaN,0
3,SKU001,Soda 500ml,Beverages,33,154.61,True,280.9,False,2024-01-04,Soda 500ml,Beverages,126.94,154.61,5,4,Thursday,False,1,1,False,4,5102.13,28.500000,28.500000,25.0,NaN,0
4,SKU001,Soda 500ml,Beverages,26,154.61,False,254.9,False,2024-01-05,Soda 500ml,Beverages,126.94,154.61,5,4,Friday,False,1,1,False,5,4019.86,28.000000,28.000000,33.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,SKU001,Soda 500ml,Beverages,71,154.61,False,60.8,False,2025-12-27,Soda 500ml,Beverages,126.94,154.61,5,4,Saturday,True,12,4,True,361,10977.31,48.714286,46.750000,35.0,67.0,0
727,SKU001,Soda 500ml,Beverages,66,154.61,False,651.2,False,2025-12-28,Soda 500ml,Beverages,126.94,154.61,5,4,Sunday,True,12,4,True,362,10204.26,50.000000,47.285714,71.0,57.0,0
728,SKU001,Soda 500ml,Beverages,46,154.61,False,605.2,False,2025-12-29,Soda 500ml,Beverages,126.94,154.61,5,4,Monday,False,12,4,True,363,7112.06,49.285714,47.607143,66.0,51.0,0
729,SKU001,Soda 500ml,Beverages,45,154.61,False,560.2,False,2025-12-30,Soda 500ml,Beverages,126.94,154.61,5,4,Tuesday,False,12,4,True,364,6957.45,48.714286,47.535714,46.0,49.0,0
730,SKU001,Soda 500ml,Beverages,41,154.61,False,519.2,False,2025-12-31,Soda 500ml,Beverages,126.94,154.61,5,4,Wednesday,False,12,4,True,365,6339.01,49.142857,47.357143,45.0,38.0,0

In [292]:

series = df_beverages['units_sold'].to_numpy(dtype=float)
date = df_beverages['date'].to_numpy()
series

train_data = series

def holt_winter(y, horizon, seasonal_periods=7):
    model=ExponentialSmoothing(
        y,
        trend='add',
        seasonal='add',
        seasonal_periods=seasonal_periods
     )
    fitted_model = model.fit()
    forecast = fitted_model.forecast(horizon)
    return np.maximum(0,forecast)

future = holt_winter(train_data,14)
x=(np.round(future,0))
print(x)

[46. 45. 55. 53. 45. 47. 47. 46. 46. 55. 53. 46. 47. 47.]

In [293]:
date

array(['2024-01-01T00:00:00.000000000', '2024-01-02T00:00:00.000000000',
       '2024-01-03T00:00:00.000000000', '2024-01-04T00:00:00.000000000',
       '2024-01-05T00:00:00.000000000', '2024-01-06T00:00:00.000000000',
       '2024-01-07T00:00:00.000000000', '2024-01-08T00:00:00.000000000',
       '2024-01-09T00:00:00.000000000', '2024-01-10T00:00:00.000000000',
       '2024-01-11T00:00:00.000000000', '2024-01-12T00:00:00.000000000',
       '2024-01-13T00:00:00.000000000', '2024-01-14T00:00:00.000000000',
       '2024-01-15T00:00:00.000000000', '2024-01-16T00:00:00.000000000',
       '2024-01-17T00:00:00.000000000', '2024-01-18T00:00:00.000000000',
       '2024-01-19T00:00:00.000000000', '2024-01-20T00:00:00.000000000',
       '2024-01-21T00:00:00.000000000', '2024-01-22T00:00:00.000000000',
       '2024-01-23T00:00:00.000000000', '2024-01-24T00:00:00.000000000',
       '2024-01-25T00:00:00.000000000', '2024-01-26T00:00:00.000000000',
       '2024-01-27T00:00:00.000000000', '2024-01-28T00:00:00.000000000',
       '2024-01-29T00:00:00.000000000', '2024-01-30T00:00:00.000000000',
       '2024-01-31T00:00:00.000000000', '2024-02-01T00:00:00.000000000',
       '2024-02-02T00:00:00.000000000', '2024-02-03T00:00:00.000000000',
       '2024-02-04T00:00:00.000000000', '2024-02-05T00:00:00.000000000',
       '2024-02-06T00:00:00.000000000', '2024-02-07T00:00:00.000000000',
       '2024-02-08T00:00:00.000000000', '2024-02-09T00:00:00.000000000',
       '2024-02-10T00:00:00.000000000', '2024-02-11T00:00:00.000000000',
       '2024-02-12T00:00:00.000000000', '2024-02-13T00:00:00.000000000',
       '2024-02-14T00:00:00.000000000', '2024-02-15T00:00:00.000000000',
       '2024-02-16T00:00:00.000000000', '2024-02-17T00:00:00.000000000',
       '2024-02-18T00:00:00.000000000', '2024-02-19T00:00:00.000000000',
       '2024-02-20T00:00:00.000000000', '2024-02-21T00:00:00.000000000',
       '2024-02-22T00:00:00.000000000', '2024-02-23T00:00:00.000000000',
       '2024-02-24T00:00:00.000000000', '2024-02-25T00:00:00.000000000',
       '2024-02-26T00:00:00.000000000', '2024-02-27T00:00:00.000000000',
       '2024-02-28T00:00:00.000000000', '2024-02-29T00:00:00.000000000',
       '2024-03-01T00:00:00.000000000', '2024-03-02T00:00:00.000000000',
       '2024-03-03T00:00:00.000000000', '2024-03-04T00:00:00.000000000',
       '2024-03-05T00:00:00.000000000', '2024-03-06T00:00:00.000000000',
       '2024-03-07T00:00:00.000000000', '2024-03-08T00:00:00.000000000',
       '2024-03-09T00:00:00.000000000', '2024-03-10T00:00:00.000000000',
       '2024-03-11T00:00:00.000000000', '2024-03-12T00:00:00.000000000',
       '2024-03-13T00:00:00.000000000', '2024-03-14T00:00:00.000000000',
       '2024-03-15T00:00:00.000000000', '2024-03-16T00:00:00.000000000',
       '2024-03-17T00:00:00.000000000', '2024-03-18T00:00:00.000000000',
       '2024-03-19T00:00:00.000000000', '2024-03-20T00:00:00.000000000',
       '2024-03-21T00:00:00.000000000', '2024-03-22T00:00:00.000000000',
       '2024-03-23T00:00:00.000000000', '2024-03-24T00:00:00.000000000',
       '2024-03-25T00:00:00.000000000', '2024-03-26T00:00:00.000000000',
       '2024-03-27T00:00:00.000000000', '2024-03-28T00:00:00.000000000',
       '2024-03-29T00:00:00.000000000', '2024-03-30T00:00:00.000000000',
       '2024-03-31T00:00:00.000000000', '2024-04-01T00:00:00.000000000',
       '2024-04-02T00:00:00.000000000', '2024-04-03T00:00:00.000000000',
       '2024-04-04T00:00:00.000000000', '2024-04-05T00:00:00.000000000',
       '2024-04-06T00:00:00.000000000', '2024-04-07T00:00:00.000000000',
       '2024-04-08T00:00:00.000000000', '2024-04-09T00:00:00.000000000',
       '2024-04-10T00:00:00.000000000', '2024-04-11T00:00:00.000000000',
       '2024-04-12T00:00:00.000000000', '2024-04-13T00:00:00.000000000',
       '2024-04-14T00:00:00.000000000', '2024-04-15T00:00:00.000000000',
       '2024-04-16T00:00:00.000000000', '2024-04-17T00:00:00.000000000',
       '2024-04-18T00:00:00.000000000', '2024-04-19T00:00:00.000000000',
       '2024-04-20T00:00:00.000000000', '2024-04-21T00:00:00.000000000',
       '2024-04-22T00:00:00.000000000', '2024-04-23T00:00:00.000000000',
       '2024-04-24T00:00:00.000000000', '2024-04-25T00:00:00.000000000',
       '2024-04-26T00:00:00.000000000', '2024-04-27T00:00:00.000000000',
       '2024-04-28T00:00:00.000000000', '2024-04-29T00:00:00.000000000',
       '2024-04-30T00:00:00.000000000', '2024-05-01T00:00:00.000000000',
       '2024-05-02T00:00:00.000000000', '2024-05-03T00:00:00.000000000',
       '2024-05-04T00:00:00.000000000', '2024-05-05T00:00:00.000000000',
       '2024-05-06T00:00:00.000000000', '2024-05-07T00:00:00.000000000',
       '2024-05-08T00:00:00.000000000', '2024-05-09T00:00:00.000000000',
       '2024-05-10T00:00:00.000000000', '2024-05-11T00:00:00.000000000',
       '2024-05-12T00:00:00.000000000', '2024-05-13T00:00:00.000000000',
       '2024-05-14T00:00:00.000000000', '2024-05-15T00:00:00.000000000',
       '2024-05-16T00:00:00.000000000', '2024-05-17T00:00:00.000000000',
       '2024-05-18T00:00:00.000000000', '2024-05-19T00:00:00.000000000',
       '2024-05-20T00:00:00.000000000', '2024-05-21T00:00:00.000000000',
       '2024-05-22T00:00:00.000000000', '2024-05-23T00:00:00.000000000',
       '2024-05-24T00:00:00.000000000', '2024-05-25T00:00:00.000000000',
       '2024-05-26T00:00:00.000000000', '2024-05-27T00:00:00.000000000',
       '2024-05-28T00:00:00.000000000', '2024-05-29T00:00:00.000000000',
       '2024-05-30T00:00:00.000000000', '2024-05-31T00:00:00.000000000',
       '2024-06-01T00:00:00.000000000', '2024-06-02T00:00:00.000000000',
       '2024-06-03T00:00:00.000000000', '2024-06-04T00:00:00.000000000',
       '2024-06-05T00:00:00.000000000', '2024-06-06T00:00:00.000000000',
       '2024-06-07T00:00:00.000000000', '2024-06-08T00:00:00.000000000',
       '2024-06-09T00:00:00.000000000', '2024-06-10T00:00:00.000000000',
       '2024-06-11T00:00:00.000000000', '2024-06-12T00:00:00.000000000',
       '2024-06-13T00:00:00.000000000', '2024-06-14T00:00:00.000000000',
       '2024-06-15T00:00:00.000000000', '2024-06-16T00:00:00.000000000',
       '2024-06-17T00:00:00.000000000', '2024-06-18T00:00:00.000000000',
       '2024-06-19T00:00:00.000000000', '2024-06-20T00:00:00.000000000',
       '2024-06-21T00:00:00.000000000', '2024-06-22T00:00:00.000000000',
       '2024-06-23T00:00:00.000000000', '2024-06-24T00:00:00.000000000',
       '2024-06-25T00:00:00.000000000', '2024-06-26T00:00:00.000000000',
       '2024-06-27T00:00:00.000000000', '2024-06-28T00:00:00.000000000',
       '2024-06-29T00:00:00.000000000', '2024-06-30T00:00:00.000000000',
       '2024-07-01T00:00:00.000000000', '2024-07-02T00:00:00.000000000',
       '2024-07-03T00:00:00.000000000', '2024-07-04T00:00:00.000000000',
       '2024-07-05T00:00:00.000000000', '2024-07-06T00:00:00.000000000',
       '2024-07-07T00:00:00.000000000', '2024-07-08T00:00:00.000000000',
       '2024-07-09T00:00:00.000000000', '2024-07-10T00:00:00.000000000',
       '2024-07-11T00:00:00.000000000', '2024-07-12T00:00:00.000000000',
       '2024-07-13T00:00:00.000000000', '2024-07-14T00:00:00.000000000',
       '2024-07-15T00:00:00.000000000', '2024-07-16T00:00:00.000000000',
       '2024-07-17T00:00:00.000000000', '2024-07-18T00:00:00.000000000',
       '2024-07-19T00:00:00.000000000', '2024-07-20T00:00:00.000000000',
       '2024-07-21T00:00:00.000000000', '2024-07-22T00:00:00.000000000',
       '2024-07-23T00:00:00.000000000', '2024-07-24T00:00:00.000000000',
       '2024-07-25T00:00:00.000000000', '2024-07-26T00:00:00.000000000',
       '2024-07-27T00:00:00.000000000', '2024-07-28T00:00:00.000000000',
       '2024-07-29T00:00:00.000000000', '2024-07-30T00:00:00.000000000',
       '2024-07-31T00:00:00.000000000', '2024-08-01T00:00:00.000000000',
       '2024-08-02T00:00:00.000000000', '2024-08-03T00:00:00.000000000',
       '2024-08-04T00:00:00.000000000', '2024-08-05T00:00:00.000000000',
       '2024-08-06T00:00:00.000000000', '2024-08-07T00:00:00.000000000',
       '2024-08-08T00:00:00.000000000', '2024-08-09T00:00:00.000000000',
       '2024-08-10T00:00:00.000000000', '2024-08-11T00:00:00.000000000',
       '2024-08-12T00:00:00.000000000', '2024-08-13T00:00:00.000000000',
       '2024-08-14T00:00:00.000000000', '2024-08-15T00:00:00.000000000',
       '2024-08-16T00:00:00.000000000', '2024-08-17T00:00:00.000000000',
       '2024-08-18T00:00:00.000000000', '2024-08-19T00:00:00.000000000',
       '2024-08-20T00:00:00.000000000', '2024-08-21T00:00:00.000000000',
       '2024-08-22T00:00:00.000000000', '2024-08-23T00:00:00.000000000',
       '2024-08-24T00:00:00.000000000', '2024-08-25T00:00:00.000000000',
       '2024-08-26T00:00:00.000000000', '2024-08-27T00:00:00.000000000',
       '2024-08-28T00:00:00.000000000', '2024-08-29T00:00:00.000000000',
       '2024-08-30T00:00:00.000000000', '2024-08-31T00:00:00.000000000',
       '2024-09-01T00:00:00.000000000', '2024-09-02T00:00:00.000000000',
       '2024-09-03T00:00:00.000000000', '2024-09-04T00:00:00.000000000',
       '2024-09-05T00:00:00.000000000', '2024-09-06T00:00:00.000000000',
       '2024-09-07T00:00:00.000000000', '2024-09-08T00:00:00.000000000',
       '2024-09-09T00:00:00.000000000', '2024-09-10T00:00:00.000000000',
       '2024-09-11T00:00:00.000000000', '2024-09-12T00:00:00.000000000',
       '2024-09-13T00:00:00.000000000', '2024-09-14T00:00:00.000000000',
       '2024-09-15T00:00:00.000000000', '2024-09-16T00:00:00.000000000',
       '2024-09-17T00:00:00.000000000', '2024-09-18T00:00:00.000000000',
       '2024-09-19T00:00:00.000000000', '2024-09-20T00:00:00.000000000',
       '2024-09-21T00:00:00.000000000', '2024-09-22T00:00:00.000000000',
       '2024-09-23T00:00:00.000000000', '2024-09-24T00:00:00.000000000',
       '2024-09-25T00:00:00.000000000', '2024-09-26T00:00:00.000000000',
       '2024-09-27T00:00:00.000000000', '2024-09-28T00:00:00.000000000',
       '2024-09-29T00:00:00.000000000', '2024-09-30T00:00:00.000000000',
       '2024-10-01T00:00:00.000000000', '2024-10-02T00:00:00.000000000',
       '2024-10-03T00:00:00.000000000', '2024-10-04T00:00:00.000000000',
       '2024-10-05T00:00:00.000000000', '2024-10-06T00:00:00.000000000',
       '2024-10-07T00:00:00.000000000', '2024-10-08T00:00:00.000000000',
       '2024-10-09T00:00:00.000000000', '2024-10-10T00:00:00.000000000',
       '2024-10-11T00:00:00.000000000', '2024-10-12T00:00:00.000000000',
       '2024-10-13T00:00:00.000000000', '2024-10-14T00:00:00.000000000',
       '2024-10-15T00:00:00.000000000', '2024-10-16T00:00:00.000000000',
       '2024-10-17T00:00:00.000000000', '2024-10-18T00:00:00.000000000',
       '2024-10-19T00:00:00.000000000', '2024-10-20T00:00:00.000000000',
       '2024-10-21T00:00:00.000000000', '2024-10-22T00:00:00.000000000',
       '2024-10-23T00:00:00.000000000', '2024-10-24T00:00:00.000000000',
       '2024-10-25T00:00:00.000000000', '2024-10-26T00:00:00.000000000',
       '2024-10-27T00:00:00.000000000', '2024-10-28T00:00:00.000000000',
       '2024-10-29T00:00:00.000000000', '2024-10-30T00:00:00.000000000',
       '2024-10-31T00:00:00.000000000', '2024-11-01T00:00:00.000000000',
       '2024-11-02T00:00:00.000000000', '2024-11-03T00:00:00.000000000',
       '2024-11-04T00:00:00.000000000', '2024-11-05T00:00:00.000000000',
       '2024-11-06T00:00:00.000000000', '2024-11-07T00:00:00.000000000',
       '2024-11-08T00:00:00.000000000', '2024-11-09T00:00:00.000000000',
       '2024-11-10T00:00:00.000000000', '2024-11-11T00:00:00.000000000',
       '2024-11-12T00:00:00.000000000', '2024-11-13T00:00:00.000000000',
       '2024-11-14T00:00:00.000000000', '2024-11-15T00:00:00.000000000',
       '2024-11-16T00:00:00.000000000', '2024-11-17T00:00:00.000000000',
       '2024-11-18T00:00:00.000000000', '2024-11-19T00:00:00.000000000',
       '2024-11-20T00:00:00.000000000', '2024-11-21T00:00:00.000000000',
       '2024-11-22T00:00:00.000000000', '2024-11-23T00:00:00.000000000',
       '2024-11-24T00:00:00.000000000', '2024-11-25T00:00:00.000000000',
       '2024-11-26T00:00:00.000000000', '2024-11-27T00:00:00.000000000',
       '2024-11-28T00:00:00.000000000', '2024-11-29T00:00:00.000000000',
       '2024-11-30T00:00:00.000000000', '2024-12-01T00:00:00.000000000',
       '2024-12-02T00:00:00.000000000', '2024-12-03T00:00:00.000000000',
       '2024-12-04T00:00:00.000000000', '2024-12-05T00:00:00.000000000',
       '2024-12-06T00:00:00.000000000', '2024-12-07T00:00:00.000000000',
       '2024-12-08T00:00:00.000000000', '2024-12-09T00:00:00.000000000',
       '2024-12-10T00:00:00.000000000', '2024-12-11T00:00:00.000000000',
       '2024-12-12T00:00:00.000000000', '2024-12-13T00:00:00.000000000',
       '2024-12-14T00:00:00.000000000', '2024-12-15T00:00:00.000000000',
       '2024-12-16T00:00:00.000000000', '2024-12-17T00:00:00.000000000',
       '2024-12-18T00:00:00.000000000', '2024-12-19T00:00:00.000000000',
       '2024-12-20T00:00:00.000000000', '2024-12-21T00:00:00.000000000',
       '2024-12-22T00:00:00.000000000', '2024-12-23T00:00:00.000000000',
       '2024-12-24T00:00:00.000000000', '2024-12-25T00:00:00.000000000',
       '2024-12-26T00:00:00.000000000', '2024-12-27T00:00:00.000000000',
       '2024-12-28T00:00:00.000000000', '2024-12-29T00:00:00.000000000',
       '2024-12-30T00:00:00.000000000', '2024-12-31T00:00:00.000000000',
       '2025-01-01T00:00:00.000000000', '2025-01-02T00:00:00.000000000',
       '2025-01-03T00:00:00.000000000', '2025-01-04T00:00:00.000000000',
       '2025-01-05T00:00:00.000000000', '2025-01-06T00:00:00.000000000',
       '2025-01-07T00:00:00.000000000', '2025-01-08T00:00:00.000000000',
       '2025-01-09T00:00:00.000000000', '2025-01-10T00:00:00.000000000',
       '2025-01-11T00:00:00.000000000', '2025-01-12T00:00:00.000000000',
       '2025-01-13T00:00:00.000000000', '2025-01-14T00:00:00.000000000',
       '2025-01-15T00:00:00.000000000', '2025-01-16T00:00:00.000000000',
       '2025-01-17T00:00:00.000000000', '2025-01-18T00:00:00.000000000',
       '2025-01-19T00:00:00.000000000', '2025-01-20T00:00:00.000000000',
       '2025-01-21T00:00:00.000000000', '2025-01-22T00:00:00.000000000',
       '2025-01-23T00:00:00.000000000', '2025-01-24T00:00:00.000000000',
       '2025-01-25T00:00:00.000000000', '2025-01-26T00:00:00.000000000',
       '2025-01-27T00:00:00.000000000', '2025-01-28T00:00:00.000000000',
       '2025-01-29T00:00:00.000000000', '2025-01-30T00:00:00.000000000',
       '2025-01-31T00:00:00.000000000', '2025-02-01T00:00:00.000000000',
       '2025-02-02T00:00:00.000000000', '2025-02-03T00:00:00.000000000',
       '2025-02-04T00:00:00.000000000', '2025-02-05T00:00:00.000000000',
       '2025-02-06T00:00:00.000000000', '2025-02-07T00:00:00.000000000',
       '2025-02-08T00:00:00.000000000', '2025-02-09T00:00:00.000000000',
       '2025-02-10T00:00:00.000000000', '2025-02-11T00:00:00.000000000',
       '2025-02-12T00:00:00.000000000', '2025-02-13T00:00:00.000000000',
       '2025-02-14T00:00:00.000000000', '2025-02-15T00:00:00.000000000',
       '2025-02-16T00:00:00.000000000', '2025-02-17T00:00:00.000000000',
       '2025-02-18T00:00:00.000000000', '2025-02-19T00:00:00.000000000',
       '2025-02-20T00:00:00.000000000', '2025-02-21T00:00:00.000000000',
       '2025-02-22T00:00:00.000000000', '2025-02-23T00:00:00.000000000',
       '2025-02-24T00:00:00.000000000', '2025-02-25T00:00:00.000000000',
       '2025-02-26T00:00:00.000000000', '2025-02-27T00:00:00.000000000',
       '2025-02-28T00:00:00.000000000', '2025-03-01T00:00:00.000000000',
       '2025-03-02T00:00:00.000000000', '2025-03-03T00:00:00.000000000',
       '2025-03-04T00:00:00.000000000', '2025-03-05T00:00:00.000000000',
       '2025-03-06T00:00:00.000000000', '2025-03-07T00:00:00.000000000',
       '2025-03-08T00:00:00.000000000', '2025-03-09T00:00:00.000000000',
       '2025-03-10T00:00:00.000000000', '2025-03-11T00:00:00.000000000',
       '2025-03-12T00:00:00.000000000', '2025-03-13T00:00:00.000000000',
       '2025-03-14T00:00:00.000000000', '2025-03-15T00:00:00.000000000',
       '2025-03-16T00:00:00.000000000', '2025-03-17T00:00:00.000000000',
       '2025-03-18T00:00:00.000000000', '2025-03-19T00:00:00.000000000',
       '2025-03-20T00:00:00.000000000', '2025-03-21T00:00:00.000000000',
       '2025-03-22T00:00:00.000000000', '2025-03-23T00:00:00.000000000',
       '2025-03-24T00:00:00.000000000', '2025-03-25T00:00:00.000000000',
       '2025-03-26T00:00:00.000000000', '2025-03-27T00:00:00.000000000',
       '2025-03-28T00:00:00.000000000', '2025-03-29T00:00:00.000000000',
       '2025-03-30T00:00:00.000000000', '2025-03-31T00:00:00.000000000',
       '2025-04-01T00:00:00.000000000', '2025-04-02T00:00:00.000000000',
       '2025-04-03T00:00:00.000000000', '2025-04-04T00:00:00.000000000',
       '2025-04-05T00:00:00.000000000', '2025-04-06T00:00:00.000000000',
       '2025-04-07T00:00:00.000000000', '2025-04-08T00:00:00.000000000',
       '2025-04-09T00:00:00.000000000', '2025-04-10T00:00:00.000000000',
       '2025-04-11T00:00:00.000000000', '2025-04-12T00:00:00.000000000',
       '2025-04-13T00:00:00.000000000', '2025-04-14T00:00:00.000000000',
       '2025-04-15T00:00:00.000000000', '2025-04-16T00:00:00.000000000',
       '2025-04-17T00:00:00.000000000', '2025-04-18T00:00:00.000000000',
       '2025-04-19T00:00:00.000000000', '2025-04-20T00:00:00.000000000',
       '2025-04-21T00:00:00.000000000', '2025-04-22T00:00:00.000000000',
       '2025-04-23T00:00:00.000000000', '2025-04-24T00:00:00.000000000',
       '2025-04-25T00:00:00.000000000', '2025-04-26T00:00:00.000000000',
       '2025-04-27T00:00:00.000000000', '2025-04-28T00:00:00.000000000',
       '2025-04-29T00:00:00.000000000', '2025-04-30T00:00:00.000000000',
       '2025-05-01T00:00:00.000000000', '2025-05-02T00:00:00.000000000',
       '2025-05-03T00:00:00.000000000', '2025-05-04T00:00:00.000000000',
       '2025-05-05T00:00:00.000000000', '2025-05-06T00:00:00.000000000',
       '2025-05-07T00:00:00.000000000', '2025-05-08T00:00:00.000000000',
       '2025-05-09T00:00:00.000000000', '2025-05-10T00:00:00.000000000',
       '2025-05-11T00:00:00.000000000', '2025-05-12T00:00:00.000000000',
       '2025-05-13T00:00:00.000000000', '2025-05-14T00:00:00.000000000',
       '2025-05-15T00:00:00.000000000', '2025-05-16T00:00:00.000000000',
       '2025-05-17T00:00:00.000000000', '2025-05-18T00:00:00.000000000',
       '2025-05-19T00:00:00.000000000', '2025-05-20T00:00:00.000000000',
       '2025-05-21T00:00:00.000000000', '2025-05-22T00:00:00.000000000',
       '2025-05-23T00:00:00.000000000', '2025-05-24T00:00:00.000000000',
       '2025-05-25T00:00:00.000000000', '2025-05-26T00:00:00.000000000',
       '2025-05-27T00:00:00.000000000', '2025-05-28T00:00:00.000000000',
       '2025-05-29T00:00:00.000000000', '2025-05-30T00:00:00.000000000',
       '2025-05-31T00:00:00.000000000', '2025-06-01T00:00:00.000000000',
       '2025-06-02T00:00:00.000000000', '2025-06-03T00:00:00.000000000',
       '2025-06-04T00:00:00.000000000', '2025-06-05T00:00:00.000000000',
       '2025-06-06T00:00:00.000000000', '2025-06-07T00:00:00.000000000',
       '2025-06-08T00:00:00.000000000', '2025-06-09T00:00:00.000000000',
       '2025-06-10T00:00:00.000000000', '2025-06-11T00:00:00.000000000',
       '2025-06-12T00:00:00.000000000', '2025-06-13T00:00:00.000000000',
       '2025-06-14T00:00:00.000000000', '2025-06-15T00:00:00.000000000',
       '2025-06-16T00:00:00.000000000', '2025-06-17T00:00:00.000000000',
       '2025-06-18T00:00:00.000000000', '2025-06-19T00:00:00.000000000',
       '2025-06-20T00:00:00.000000000', '2025-06-21T00:00:00.000000000',
       '2025-06-22T00:00:00.000000000', '2025-06-23T00:00:00.000000000',
       '2025-06-24T00:00:00.000000000', '2025-06-25T00:00:00.000000000',
       '2025-06-26T00:00:00.000000000', '2025-06-27T00:00:00.000000000',
       '2025-06-28T00:00:00.000000000', '2025-06-29T00:00:00.000000000',

In [294]:
last_date =df_beverages['date'][730]
print(last_date)

2025-12-31 00:00:00

In [295]:
future_dates = pd.date_range(
    start= last_date + pd.Timedelta(days=1),
    periods=len(future),
    freq='D'
)
print(future_dates)

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14'],
              dtype='datetime64[ns]', freq='D')

In [296]:
forecasted_table = pd.DataFrame({'Date':future_dates,
                                 'units_sold':x})
forecasted_table

         Date  units_sold
0  2026-01-01        46.0
1  2026-01-02        45.0
2  2026-01-03        55.0
3  2026-01-04        53.0
4  2026-01-05        45.0
5  2026-01-06        47.0
6  2026-01-07        47.0
7  2026-01-08        46.0
8  2026-01-09        46.0
9  2026-01-10        55.0
10 2026-01-11        53.0
11 2026-01-12        46.0
12 2026-01-13        47.0
13 2026-01-14        47.0

In [298]:
forecasted_table.to_csv(r'C:\Users\ahmed\Documents\Data Science LUXDEV\PPORTFOLIO PROJECTS\INVENTORY FORECASTING\CSV\CLEAN\forecasted_values.csv',index=False)